
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/

# HTTP Server
server:
  port: 11001   # HTTP (Tomcat) port
  
spring:
  application:
    name: user-service
  datasource:
    url : jdbc:postgresql://localhost:5432/csusers
    username: postgres
    password: haslo1
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true

  database:
    driverClassName:org.postgresql.Driver
